### ISSUE TITLE
PSVR headset not detected

### ISSUE THREAD

**Issue by LinusMOGEL** [HipsterSloth/PSVRTracker#22]
Hi there i,ve intalled PSVRTracker. When I switch to "PS3-Eye Video Interface" drivers it does`s not show up. i tried to change:

- {
	"version":              1,
	"usb_api":              ",linusb_api:,
	"enable_usb_transfers": true
}

- "version":              1,
	"usb_api":              ",winusb_api:,
	"enable_usb_transfers": true

It does not work. Then I saw this 
#3 
![45582271-a4249700-b861-11e8-9583-8ad0edee2df2](https://user-images.githubusercontent.com/49592740/57182798-04755100-6ea4-11e9-8ee3-02fbc1013060.png)

I heard that you @HipsterSloth said that you need to replace hidUsb drivers with Winusb.
the problem is that it still not working. I Downloaded the Alpha version but it seems to be the same I could no longer run Trinus with my headset, someone help!

**Comment by mick-p1982** [comment]
I'm sorry. This is a research project. We're trying to be the first to do serious things with camera based tracking on PC. It's goal is similar to the defunct PSVRToolbox, which you can use for some minor things out of the box like controlling the home-theater mode, but is still for PSVR (on PC) developers primarily. If we succeed the result will probably end up in PSMoveService or https://github.com/HipsterSloth/PSMoveSteamVRBridge.

To do development you want the latest source code here. It may or may not conflict with Trinus PSVR. I can't recall if it did or not when I tried out Trinus a little while back.

**Comment by LinusMOGEL** [comment]
It was ictually my fault I didnt saw that it was in a unusable state.
